from numpy.typing import ArrayLike, NDArray
import numpy as np
from . import io as io

__version__: str

class PrePostEdge:
    def __init__(self) -> None: ...
    pre_edge_start: float | None
    pre_edge_end: float | None
    norm_start: float | None
    norm_end: float | None
    norm_polyorder: int | None
    n_victoreen: int | None
    e0: float | None
    edge_step: float | None

class AUTOBK:
    def __init__(self) -> None: ...
    ek0: float | None
    rbkg: float | None
    nknots: int | None
    kmin: float | None
    kmax: float | None
    kstep: float | None
    nclamp: int | None
    clamp_lo: int | None
    clamp_hi: int | None
    clamp_lambda: float | None
    nfft: int | None
    kweight: int | None
    dk: float | None
    linear_regularization: float | None
    linear_condition_limit: float | None
    linear_residual_ratio_limit: float | None
    linear_fallback_to_lm: bool | None
    linear_workspace_cache: bool | None
    window: str | None
    solver: str | None
    linear_fallback_solver: str | None
    clamp_scale_policy: str | None

class XrayFFTF:
    def __init__(self) -> None: ...
    rmax_out: float | None
    dk: float | None
    dk2: float | None
    kmin: float | None
    kmax: float | None
    kweight: float | None
    nfft: int | None
    kstep: float | None
    window: str | None

class NormalizationMethod:
    @staticmethod
    def PrePostEdge(parameters: PrePostEdge) -> NormalizationMethod: ...
    @staticmethod
    def new_prepostedge() -> NormalizationMethod: ...
    @staticmethod
    def new_mback() -> NormalizationMethod: ...

class BackgroundMethod:
    @staticmethod
    def AUTOBK(parameters: AUTOBK) -> BackgroundMethod: ...
    @staticmethod
    def new_autobk() -> BackgroundMethod: ...
    @staticmethod
    def new_ilpbkg() -> BackgroundMethod: ...

class Spectrum:
    def __init__(self, energy: ArrayLike, mu: ArrayLike) -> None: ...
    @staticmethod
    def from_arrays(energy: ArrayLike, mu: ArrayLike) -> Spectrum: ...
    def set_spectrum(self, energy: ArrayLike, mu: ArrayLike) -> Spectrum: ...
    def set_e0(self, e0: float) -> Spectrum: ...
    def set_normalization_method(self, method: NormalizationMethod | None = None) -> Spectrum: ...
    def set_background_method(self, method: BackgroundMethod | None = None) -> Spectrum: ...
    def set_fft(self, parameters: XrayFFTF) -> Spectrum: ...
    def e0(self) -> float | None: ...
    def find_e0(self) -> Spectrum: ...
    def normalize(self) -> Spectrum: ...
    def calc_background(self) -> Spectrum: ...
    def fft(self) -> Spectrum: ...
    def ifft(self) -> Spectrum: ...
    def invalidate_derived(self) -> Spectrum: ...
    def k(self) -> NDArray[np.float64] | None: ...
    def chi(self) -> NDArray[np.float64] | None: ...
    def norm(self) -> NDArray[np.float64] | None: ...
    def flat(self) -> NDArray[np.float64] | None: ...
    def pre_edge(self) -> NDArray[np.float64] | None: ...
    def post_edge(self) -> NDArray[np.float64] | None: ...
    def r(self) -> NDArray[np.float64] | None: ...
    def chir_mag(self) -> NDArray[np.float64] | None: ...
    def chir_real(self) -> NDArray[np.float64] | None: ...
    def chir_imag(self) -> NDArray[np.float64] | None: ...
    def q(self) -> NDArray[np.float64] | None: ...
    def chiq(self) -> NDArray[np.float64] | None: ...
